### ISSUE TITLE
Setup Bugs

### ISSUE THREAD

**Issue by pavog** [andersspielen/PotionGamesIssues#16]
Hi, after I ran `/pg setup` I receive the following errors in my console:

```
[Server thread/WARN]: [PotionGames] Task #2 for PotionGames v6.0.3 generated an exception
--
57 | java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockState cannot be cast to class org.bukkit.block.Sign (org.bukkit.craftbukkit.v1_18_R2.block.CraftBlockState and org.bukkit.block.Sign are in unnamed module of loader java.net.URLClassLoader @5680a178)
58 | at com.asga.potiongames.main.PotionGames.lambda$tick$2(PotionGames.java:2142) ~[PotionGames-6.0.3.jar:?]
59 | at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-333]
60 | at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-333]
61 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-333]
62 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-333]
63 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-333]
64 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-333]
65 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
66 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Full log:
https://mclo.gs/6aK83fp

**Comment by lnnrtbln** [comment]
Fixed in newer versions! These errors can occur if the lobby/s are not fully set up!
More error prevention is going to happen in version 6.0.6. Version 6.0.5 is only an update for official Minecraft 1.19 support.

**Comment by lennartabeln** [comment]
Prevented in [Version 6.0.6](https://github.com/andersspielen/PotionGamesIssues/releases/tag/6.0.6)
